---
- name: Installing and Launch Metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat deb
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Copying metricbeat to Web VM
    copy:
      src: /etc/ansible/files/metricbeat.config
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure the docker module
    command: sudo metricbeat modules enable docker

  - name: metricbeat setup
    command: metricbeat setup

  - name: metricbeat start
    command: service metricbeat start

  - name: Enable metricbeat service
    systemd:
      name: metricbeat
      enabled: yes
